// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GlucaEase",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GlucaEase",
            targets: ["AppModule"],
            bundleIdentifier: "hj.eventKitExploration",
            teamIdentifier: "G8G52698W5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .calendars(purposeString: "\"Allow app to access calenders to set a reminder\""),
                .reminders(purposeString: "\"Allow app to access reminders to set reminders\"")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)